<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FC0ODHN" failures="1" tests="8" name="apicalls.TC01_API_HealthCheck" time="2.564" errors="0" timestamp="2022-11-05T00:20:03 EDT" skipped="0">
  <testcase classname="apicalls.TC01_API_HealthCheck" name="TestForAPIhealth" time="1.002"/>
  <system-out/>
  <testcase classname="apicalls.TC01_API_HealthCheck" name="TestForAPIhealth" time="0.009"/>
  <system-out/>
  <testcase classname="apicalls.TC01_API_HealthCheck" name="Register_User" time="0.579"/>
  <system-out/>
  <testcase classname="apicalls.TC01_API_HealthCheck" name="getToken" time="0.851"/>
  <system-out/>
  <testcase classname="apicalls.TC01_API_HealthCheck" name="Add_New_GiftCard" time="0.021"/>
  <system-out/>
  <testcase classname="apicalls.TC01_API_HealthCheck" name="GetSpecific_Giftcard" time="0.039"/>
  <system-out/>
  <testcase classname="apicalls.TC01_API_HealthCheck" name="GetAllGiftcard" time="0.038"/>
  <system-out/>
  <testcase classname="apicalls.TC01_API_HealthCheck" name="Delete_A_Giftcard" time="0.025">
    <failure message="Expected: &lt;null&gt; but was: Delete Success" type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError: Expected: <null> but was: Delete Success
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertNull(Assert.java:237)
at junit.framework.Assert.assertNull(Assert.java:230)
at apicalls.TC01_API_HealthCheck.Delete_A_Giftcard(TC01_API_HealthCheck.java:322)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Delete_A_Giftcard -->
  <system-out/>
</testsuite> <!-- apicalls.TC01_API_HealthCheck -->
